### ISSUE TITLE
Gradle Daemon DIES !

### ISSUE THREAD

**Issue by aminecmi** [aminecmi/ReaderforSelfoss#167]
```
09:42:00 org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
09:42:00 	at org.gradle.launcher.daemon.client.DaemonClient.handleDaemonDisappearance(DaemonClient.java:238)
09:42:00 	at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:214)
09:42:00 	at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:178)
09:42:00 	at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:56)
09:42:00 	at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:38)
09:42:00 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
09:42:00 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
09:42:00 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:287)
09:42:00 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:260)
09:42:00 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:33)
09:42:00 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
09:42:00 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
09:42:00 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
09:42:00 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:253)
09:42:00 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:182)
09:42:00 	at org.gradle.launcher.Main.doAction(Main.java:33)
09:42:00 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
09:42:00 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:42:00 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:42:00 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:42:00 	at java.lang.reflect.Method.invoke(Method.java:498)
09:42:00 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
09:42:00 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
09:42:00 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
09:42:00 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:42:00 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:42:00 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:42:00 	at java.lang.reflect.Method.invoke(Method.java:498)
09:42:00 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
09:42:00 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
09:42:00 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61) 
```

**Comment by aminecmi** [comment]
This seams to be fixed somehow.
