### ISSUE TITLE
The notification bar icon as well as the notification itself dont disappear anymore. Only way to close them is to force the app to stop via android app details. Works only temporarily though.

### ISSUE THREAD

**Issue by aminecmi** [aminecmi/ReaderforSelfoss#324]
See #322 

May be related to images cashing.

**Comment by davidoskky** [comment]
This is most probably related to image caching, but I cannot reproduce the issue.
It may be that the application is trying to cache more images than allowed by the cache maximum dimension

**Comment by davidoskky** [comment]
I'll be working on this: I will let it sync only images from unread articles and provide a hard limit to the number of images to sync.
 
> Cache is approximately 10 MB. Don't know how many articles there are in total...700 - 1000 maybe.
BTW... Clearing the cache didn't help man_shrugging

This however makes me think that the cache dimension is not the only problem, as I would otherwise expect 200 MB cache.

**Comment by aminecmi** [comment]
@davidoskky I'll try to provide a selfoss instance for testing purposes with a lot of unread articles and images.

**Comment by aminecmi** [comment]
I did get the app to crash, just by running it. The notification did stay on. 
```
2021-01-09 11:41:08.034 15032-15032/apps.amine.bou.readerforselfoss W/Glide: Load failed for https://img.linuxfr.org/img/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f652f65392f4379616e6f67656e5f496e632e5f6c6f676f5f253238323031342d323031352532392e737667/Cyanogen_Inc._logo_%282014-2015%29.svg with size [-2147483648x-2147483648]
    class com.bumptech.glide.load.engine.GlideException: Failed to load resource
      Cause (1 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Bitmap->Bitmap}, DATA_DISK_CACHE, https://img.linuxfr.org/img/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f652f65392f4379616e6f67656e5f496e632e5f6c6f676f5f253238323031342d323031352532392e737667/Cyanogen_Inc._logo_%282014-2015%29.svg
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Bitmap}
      Cause (2 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Bitmap->Bitmap}, DATA_DISK_CACHE, https://img.linuxfr.org/img/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f652f65392f4379616e6f67656e5f496e632e5f6c6f676f5f253238323031342d323031352532392e737667/Cyanogen_Inc._logo_%282014-2015%29.svg
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Bitmap}
      Cause (3 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Bitmap->Bitmap}, DATA_DISK_CACHE, https://img.linuxfr.org/img/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f652f65392f4379616e6f67656e5f496e632e5f6c6f676f5f253238323031342d323031352532392e737667/Cyanogen_Inc._logo_%282014-2015%29.svg
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Bitmap}
      Cause (4 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{DirectByteBuffer->Bitmap->Bitmap}, REMOTE, https://img.linuxfr.org/img/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f652f65392f4379616e6f67656e5f496e632e5f6c6f676f5f253238323031342d323031352532392e737667/Cyanogen_Inc._logo_%282014-2015%29.svg
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{DirectByteBuffer->Bitmap->Bitmap}
      Cause (5 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{FileInputStream->Bitmap->Bitmap}, REMOTE, https://img.linuxfr.org/img/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f652f65392f4379616e6f67656e5f496e632e5f6c6f676f5f253238323031342d323031352532392e737667/Cyanogen_Inc._logo_%282014-2015%29.svg
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{FileInputStream->Bitmap->Bitmap}
      Cause (6 of 6): class com.bumptech.glide.load.engine.GlideException: Failed LoadPath{ParcelFileDescriptor->Bitmap->Bitmap}, REMOTE, https://img.linuxfr.org/img/68747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f652f65392f4379616e6f67656e5f496e632e5f6c6f676f5f253238323031342d323031352532392e737667/Cyanogen_Inc._logo_%282014-2015%29.svg
        Cause (1 of 1): class com.bumptech.glide.load.engine.GlideException: Failed DecodePath{ParcelFileDescriptor->Bitmap->Bitmap}
2021-01-09 11:41:08.037 15032-15149/apps.amine.bou.readerforselfoss E/AndroidRuntime: FATAL EXCEPTION: Thread-22
    Process: apps.amine.bou.readerforselfoss, PID: 15032
    java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Load failed
        at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:206)
        at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:108)
        at apps.amine.bou.readerforselfoss.api.selfoss.Item.preloadImages(SelfossModels.kt:160)
        at apps.amine.bou.readerforselfoss.background.LoadingWorker$doWork$1$onResponse$1.invoke(background.kt:108)
        at apps.amine.bou.readerforselfoss.background.LoadingWorker$doWork$1$onResponse$1.invoke(background.kt:69)
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
     Caused by: java.lang.IllegalStateException: Load failed
        at com.bumptech.glide.request.RequestFutureTarget.doGet(RequestFutureTarget.java:206) 
        at com.bumptech.glide.request.RequestFutureTarget.get(RequestFutureTarget.java:108) 
        at apps.amine.bou.readerforselfoss.api.selfoss.Item.preloadImages(SelfossModels.kt:160) 
        at apps.amine.bou.readerforselfoss.background.LoadingWorker$doWork$1$onResponse$1.invoke(background.kt:108) 
        at apps.amine.bou.readerforselfoss.background.LoadingWorker$doWork$1$onResponse$1.invoke(background.kt:69) 
        at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30) 
```

**Comment by davidoskky** [comment]
Could you give me the link you use to access the feed of linuxfr? I cannot find it on their website...

**Comment by aminecmi** [comment]
@davidoskky this should be the rss source https://www.journalduhacker.net/rss
