### ISSUE TITLE
App stoped working with older Android versions

### ISSUE THREAD

**Issue by aminecmi** [aminecmi/ReaderforSelfoss#376]
Just after the login screen, the app closes with the error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
        at com.burgstaller.okhttp.digest.DigestAuthenticator.<init>(DigestAuthenticator.java:87)
        at apps.amine.bou.readerforselfoss.api.selfoss.SelfossApi.createAuthenticator(SelfossApi.kt:56)
        at apps.amine.bou.readerforselfoss.api.selfoss.SelfossApi.<init>(SelfossApi.kt:89)
        at apps.amine.bou.readerforselfoss.LoginActivity.attemptLogin(LoginActivity.kt:206)
        at apps.amine.bou.readerforselfoss.LoginActivity.handleActions$lambda-2(LoginActivity.kt:88)
        at apps.amine.bou.readerforselfoss.LoginActivity.$r8$lambda$EsPlmfqElKz5Phud-MnD4g7RyMs(LoginActivity.kt)
        at apps.amine.bou.readerforselfoss.LoginActivity$$ExternalSyntheticLambda2.onClick(Unknown Source)
        at android.view.View.performClick(View.java:4204)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1120)
        at android.view.View$PerformClick.run(View.java:17355)
        at android.os.Handler.handleCallback(Handler.java:725)
        at android.os.Handler.dispatchMessage(Handler.java:92)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5041)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
        at dalvik.system.NativeStart.main(Native Method)

```

This may be due to version updates.

**Comment by davidoskky** [comment]
This is due to the dependencies updates.
okhttp3 dropped support of apis lower than 21.

I see three options:
- Downgrade it to version 3.12.13
- Drop support of older android versions, this would be android 4 and previous
- Remove the library from the application, if that's possible

Downgrading the library doesn't immediately solve the issue for some reason, thus some further modifications may be required.

**Comment by aminecmi** [comment]
@davidoskky I think that we can change the minSdk to 21.

okhttp is needed for retrofit calls, so we can't change it easilly.

Changing the minSdk would fix the issue.

**Comment by aminecmi** [comment]
By doing this, we would close #339 too.
